---
- name: Create project folder
  become: true
  copy:
    src: ../files/docker-services/
    dest: /src/
    # state: directory
    owner: docker
    group: docker
    mode: "0777"

# - name: Copy docker files
#   become: true
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: "{{ item.owner }}"
#     group: "{{ item.group }}"
#     mode: "{{ item.mode }}"
#   loop:
#     - src: ../files/docker-services/docker-compose.yaml
#       dest: /src/docker-compose.yaml
#       owner: docker
#       group: docker
#       mode: "0550"
#     - src: ../files/docker-services/.env
#       dest: /src/.env
#       owner: docker
#       group: docker
#       mode: "0550"
#     - src: ../files/docker-services/traefik/
#       dest: /src/traefik/
#       owner: docker
#       group: docker
#       mode: "0550"
#     - src: ../files/docker-services/nodered/
#       dest: /src/nodered/
#       owner: "1000"
#       group: "1000"
#       mode: "0770"
- name: deploy Docker Compose stack
  become: true
  become_user: docker
  community.docker.docker_compose:
    project_src: /src/
    files:
      - docker-compose.yaml
