---
- hosts: all
  gather_facts: false
  name: all hosts default setup

  vars_files:
    - config.yml
    - vault.yml

  tasks:
    - name: Add user
      include_tasks: tasks/user.yml

    - name: Update and install default software
      include_tasks: tasks/software/default.yml

- hosts: ctl
  gather_facts: false
  name: install jury controller

  vars_files:
    - vault.yml

  tasks:
    - name: Install controller
      include_tasks: tasks/software/controller.yml

- hosts: server
  gather_facts: false
  name: install docker services

  vars_files:
    - vault.yml

  tasks:
    - name: Start Docker Services
      include_tasks: tasks/docker-services.yml
